#pragma once

extern "C" HRESULT APIENTRY OpenAdapter10( D3D10DDIARG_OPENADAPTER * arg1 );
extern "C" HRESULT APIENTRY OpenAdapter10_2( D3D10DDIARG_OPENADAPTER * arg1 );
EXTERN_C _Check_return_ NTSTATUS APIENTRY D3DKMTCreateDevice( _Inout_ D3DKMT_CREATEDEVICE* );
EXTERN_C _Check_return_ NTSTATUS APIENTRY D3DKMTOpenAdapterFromGdiDisplayName( _Inout_ D3DKMT_OPENADAPTERFROMGDIDISPLAYNAME* );
EXTERN_C _Check_return_ NTSTATUS APIENTRY D3DKMTOpenAdapterFromDeviceName( _Inout_ D3DKMT_OPENADAPTERFROMDEVICENAME* );
EXTERN_C _Check_return_ NTSTATUS APIENTRY D3DKMTQueryAdapterInfo( _Inout_ CONST D3DKMT_QUERYADAPTERINFO* );